name: cybear-jinni
version: '1.0'
summary: App to control your smart device through CyBear Jinni Hub
description: Single app to control smart device from different form factor through CyBear Jinni Hub

grade: stable  # devel/stable, must be 'stable' to release into candidate/stable channels
confinement: strict  # devmode/classic/strict, use 'strict' once you have the right plugs and slots


base: core18

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  cybear-jinni:
    plugin: flutter
    source: https://github.com/CyBear-Jinni/CBJ_App.git
    flutter-target: lib/main.dart
    override-build: |
      flutter clean
      flutter pub get
      flutter pub run build_runner build --delete-conflicting-outputs
      rm -rf build
      rm -r linux/flutter/ephemeral/
      snapcraftctl build

apps:
  cybear-jinni:
    command: CyBear-Jinni_App
    extensions: [flutter-master]
    plugs: [network, network-bind, network-manager, desktop-legacy, unity7]