name: cybear-jinni
version: '1.0'
summary: App to control your smart device through CyBear Jinni Hub
description: Single app to control smart device from different form factor through CyBear Jinni Hub

confinement: devmode

base: core18

parts:
  cybear-jinni:
    plugin: flutter
    source: https://github.com/CyBear-Jinni/CBJ_App.git
    flutter-target: lib/main.dart
    override-build: |
      flutter pub get
      flutter pub run build_runner build --delete-conflicting-outputs
      snapcraftctl build

apps:
  cybear-jinni:
    command: cybear_jinni
    extensions: [flutter-dev]